# Generated by Django 3.2.5 on 2021-10-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_app', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_link', models.TextField(max_length=256)),
                ('photo_link', models.TextField(max_length=256)),
                ('chinese_name', models.TextField(max_length=256)),
                ('origin_name', models.TextField(max_length=256)),
                ('score', models.FloatField(max_length=256)),
                ('rated', models.TextField(max_length=256)),
                ('introduction', models.TextField(max_length=256)),
                ('actors', models.TextField(max_length=256)),
            ],
            options={
                'verbose_name': '豆瓣电影前250',
                'verbose_name_plural': '爬虫获取数据',
            },
        ),
    ]
