# Generated by Django 3.2.5 on 2021-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
            ],
        ),
    ]
