# Generated by Django 3.2.5 on 2021-10-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
