# Generated by Django 3.2.5 on 2021-10-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211014_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_account',
            options={'ordering': ['time_created'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
