# Generated by Django 3.2.5 on 2021-10-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_account_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='introduction',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='phone',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='photo',
            field=models.ImageField(upload_to='png/'),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=128),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
