# Generated by Django 3.2.5 on 2021-10-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.CharField(max_length=128)),
            ],
        ),
    ]
