# Generated by Django 3.2.5 on 2021-10-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
