# Generated by Django 3.2.5 on 2021-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='up_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '超级用户',
                'verbose_name_plural': '超级用户',
                'ordering': ['time_created'],
            },
        ),
    ]
